# This is a basic workflow that is manually triggered

name: Create release tag

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      bumping_part:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'major, minor or patch'
        # Default value if no value is explicitly provided
        default: 'minor'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 履歴を全て見たい
      - name: Install dependencies
        run: yarn install
      - name: run lerna-changelog
        id: run_changelog
        run: |
          changelog=`yarn run lerna-changelog`
          echo "$changelog"
          echo "::set-output name=changelog::${changelog//$'\n'/\\n}";
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.bumping_part }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.run_changelog.outputs.changelog }}

